<a href="https://colab.research.google.com/github/jinunyachhyon/Deep-Learning-with-Tensorflow/blob/main/TensorFlow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes."

# Rank/Degree of Tensors
Another word of rank is degree, these terms simply mean the number of dimensions ivolved in the tensor.

In [1]:
import tensorflow as tf

In [2]:
rank_1_tensor = tf.Variable(['test','for','rank'], tf.string)
rank_2_tensor = tf.Variable(['test','rank'],['rank','two'], tf.string)

In [3]:
rank_1_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'test', b'for', b'rank'], dtype=object)>

**To determine the rank of tensor we can call the following method:**

In [4]:
tf.rank(rank_1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

# Shape of tensor and Changing it

In [5]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape existing tensors

tensor3 = tf.reshape(tensor2, [3,-1]) # -1 tells the tensor to calculate the size of the dimension in that place 

In [6]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Core Learning Algorithms

In [8]:
import pandas as pd

# Load dataset
dftrain = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/train.csv') # Training data
dfeval = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/eval.csv') # Testing data

dftrain.head()

survived     sex   age  n_siblings_spouses  parch     fare  class     deck  \
0         0    male  22.0                   1      0   7.2500  Third  unknown   
1         1  female  38.0                   1      0  71.2833  First        C   
2         1  female  26.0                   0      0   7.9250  Third  unknown   
3         1  female  35.0                   1      0  53.1000  First        C   
4         0    male  28.0                   0      0   8.4583  Third  unknown   

   embark_town alone  
0  Southampton     n  
1    Cherbourg     n  
2  Southampton     y  
3  Southampton     n  
4   Queenstown     y